permalink: pretty
title: kosfar's Blog
tagline: A systems traveller logbook
description: >-
  "A logbook originally referred to a book for recording readings from the chip log,
  used to determine the distance a ship traveled within a certain amount of time."
  
  -- Wikipedia
url: 'https://kosfar.github.io'
baseurl: ''
paginate: 5

author:
  name: Kostis Fardelas
  url: 'https://kosfar.github.io'


github:
  repo: 'https://github.com/kosfar/kosfar.github.io'

version: 1.0.0

plugins:
  - jekyll-paginate
  - jekyll-admin


excerpt_separator: <!--more-->
